// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Entities
{
    using System;

    // OptionChoice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class OptionChoice
    {
        public int OptionChoiceId { get; set; } // OptionChoiceId (Primary key)
        public string OptionChoiceLabel { get; set; } // OptionChoiceLabel
        public bool IsDropdown { get; set; } // IsDropdown

        public OptionChoice()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
