// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Entities
{
    using System;

    // Survey
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class Survey
    {
        public int SurveyId { get; set; } // SurveyId (Primary key)
        public string UniqueId { get; set; } // UniqueId
        public string Name { get; set; } // Name
        public string Description { get; set; } // Description
        public string Logo { get; set; } // Logo
        public int OrganizationId { get; set; } // OrganizationId
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string ModifiedBy { get; set; } // ModifiedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string DeletedBy { get; set; } // DeletedBy
        public System.DateTime? DeletedOn { get; set; } // DeletedOn
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<GroupSurvey> GroupSurveys { get; set; } // GroupSurvey.FK_dbo.GroupSurvey_dbo.Survey_SurveyId
        public virtual System.Collections.Generic.ICollection<SurveySection> SurveySections { get; set; } // SurveySection.FK_dbo.SurveySection_dbo.Survey_SurveyId

        // Foreign keys
        public virtual Organization Organization { get; set; } // FK_dbo.Survey_dbo.Organization_OrganizationId

        public Survey()
        {
            GroupSurveys = new System.Collections.Generic.List<GroupSurvey>();
            SurveySections = new System.Collections.Generic.List<SurveySection>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
