// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace MigrationDemo
{

    public class Symbol
    {
        public int C36 { get; set; }
        public System.Nullable<int> C37 { get; set; }
        public System.Nullable<int> C163 { get; set; }
        public System.Nullable<int> C38Test36 { get; set; }
        public string Description { get; set; }
    }

}
// </auto-generated>
