// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace MigrationDemo
{

    public class TableWithSpaceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TableWithSpace>
    {
        public TableWithSpaceConfiguration()
            : this("dbo")
        {
        }
 
        public TableWithSpaceConfiguration(string schema)
        {
            ToTable(schema + ".table with space");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            HasMany(t => t.TableWithSpaceAndInColumns).WithMany(t => t.TableWithSpaces).Map(m => 
            {
                m.ToTable("table mapping with space", "dbo");
                m.MapLeftKey("id");
                m.MapRightKey("id value");
            });
        }
    }

}
// </auto-generated>
