// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    // Answer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class Answer
    {

        ///<summary>
        /// AnswerId (Primary key)
        ///</summary>
        public int AnswerId { get; set; }

        ///<summary>
        /// QuestionId
        ///</summary>
        public int? QuestionId { get; set; }

        ///<summary>
        /// QuestionOptionId
        ///</summary>
        public int? QuestionOptionId { get; set; }

        ///<summary>
        /// AnswerValue
        ///</summary>
        public string AnswerValue { get; set; }

        ///<summary>
        /// CreatedBy
        ///</summary>
        public string CreatedBy { get; set; }

        ///<summary>
        /// CreatedOn
        ///</summary>
        public System.DateTime CreatedOn { get; set; }

        ///<summary>
        /// ModifiedBy
        ///</summary>
        public string ModifiedBy { get; set; }

        ///<summary>
        /// ModifiedOn
        ///</summary>
        public System.DateTime? ModifiedOn { get; set; }

        ///<summary>
        /// DeletedBy
        ///</summary>
        public string DeletedBy { get; set; }

        ///<summary>
        /// DeletedOn
        ///</summary>
        public System.DateTime? DeletedOn { get; set; }

        ///<summary>
        /// IsDeleted
        ///</summary>
        public bool? IsDeleted { get; set; }

        ///<summary>
        /// Comment
        ///</summary>
        public string Comment { get; set; }

        ///<summary>
        /// SurveyeeGuid (length: 36)
        ///</summary>
        public string SurveyeeGuid { get; set; }

        ///<summary>
        /// MatrixColId
        ///</summary>
        public int? MatrixColId { get; set; }

        ///<summary>
        /// MatrixRowId
        ///</summary>
        public int? MatrixRowId { get; set; }

        // Foreign keys
        public virtual Question Question { get; set; } // FK_Answer_Question
        public virtual QuestionOption QuestionOption { get; set; } // FK_Answer_QuestionOption

        public Answer()
        {
            CreatedOn = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
