// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{
    using System;

    // Answer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class Answer
    {
        public int AnswerId { get; set; } // AnswerId (Primary key)
        public int? QuestionId { get; set; } // QuestionId
        public int? QuestionOptionId { get; set; } // QuestionOptionId
        public string AnswerValue { get; set; } // AnswerValue
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime CreatedOn { get; set; } // CreatedOn
        public string ModifiedBy { get; set; } // ModifiedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string DeletedBy { get; set; } // DeletedBy
        public System.DateTime? DeletedOn { get; set; } // DeletedOn
        public bool? IsDeleted { get; set; } // IsDeleted
        public string Comment { get; set; } // Comment
        public string SurveyeeGuid { get; set; } // SurveyeeGuid (length: 36)
        public int? MatrixColId { get; set; } // MatrixColId
        public int? MatrixRowId { get; set; } // MatrixRowId

        // Foreign keys
        public virtual Question Question { get; set; } // FK_Answer_Question
        public virtual QuestionOption QuestionOption { get; set; } // FK_Answer_QuestionOption

        public Answer()
        {
            CreatedOn = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
