// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    // Group
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class Group
    {

        ///<summary>
        /// GroupId (Primary key)
        ///</summary>
        public int GroupId { get; set; }

        ///<summary>
        /// Code
        ///</summary>
        public string Code { get; set; }

        ///<summary>
        /// Name
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        /// CreatedBy
        ///</summary>
        public string CreatedBy { get; set; }

        ///<summary>
        /// CreatedOn
        ///</summary>
        public System.DateTime? CreatedOn { get; set; }

        ///<summary>
        /// ModifiedBy
        ///</summary>
        public string ModifiedBy { get; set; }

        ///<summary>
        /// ModifiedOn
        ///</summary>
        public System.DateTime? ModifiedOn { get; set; }

        ///<summary>
        /// DeletedBy
        ///</summary>
        public string DeletedBy { get; set; }

        ///<summary>
        /// DeletedOn
        ///</summary>
        public System.DateTime? DeletedOn { get; set; }

        ///<summary>
        /// IsActive
        ///</summary>
        public bool IsActive { get; set; }

        ///<summary>
        /// IsDeleted
        ///</summary>
        public bool IsDeleted { get; set; }

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<GroupSurvey> GroupSurveys { get; set; } // GroupSurvey.FK_dbo.GroupSurvey_dbo.Group_GroupId
        public virtual System.Collections.Generic.ICollection<UserGroup> UserGroups { get; set; } // UserGroup.FK_dbo.UserGroup_dbo.Group_GroupId

        public Group()
        {
            GroupSurveys = new System.Collections.Generic.List<GroupSurvey>();
            UserGroups = new System.Collections.Generic.List<UserGroup>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
