// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{
    using System;

    // MatrixRow
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class MatrixRowMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MatrixRow>
    {
        public MatrixRowMapping()
            : this("dbo")
        {
        }

        public MatrixRowMapping(string schema)
        {
            ToTable("MatrixRow", schema);
            HasKey(x => x.RowId);

            Property(x => x.RowId).HasColumnName(@"RowId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RowLabel).HasColumnName(@"RowLabel").IsOptional().HasColumnType("nvarchar");
            Property(x => x.QuestionId).HasColumnName(@"QuestionId").IsRequired().HasColumnType("int");
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").IsOptional().HasColumnType("datetime");
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").IsOptional().HasColumnType("datetime");

            // Foreign keys
            HasRequired(a => a.Question).WithMany(b => b.MatrixRows).HasForeignKey(c => c.QuestionId); // FK_dbo.MatrixRow_dbo.Question_QuestionId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
