// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    // OptionError
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class OptionError
    {

        ///<summary>
        /// OptionErrorId (Primary key)
        ///</summary>
        public int OptionErrorId { get; set; }

        ///<summary>
        /// QuestionOptionId
        ///</summary>
        public int QuestionOptionId { get; set; }

        ///<summary>
        /// ErrorText
        ///</summary>
        public string ErrorText { get; set; }

        public OptionError()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
