// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{
    using System;

    // PredefinedDropdown
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class PredefinedDropdown
    {
        public int PredefinedDropdownId { get; set; } // PredefinedDropdownId (Primary key)
        public string Name { get; set; } // Name
        public string TableName { get; set; } // TableName
        public string ColumnName { get; set; } // ColumnName

        public PredefinedDropdown()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
