// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    // QuestionOption
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class QuestionOption
    {

        ///<summary>
        /// QuestionOptionId (Primary key)
        ///</summary>
        public int QuestionOptionId { get; set; }

        ///<summary>
        /// OptionChoiceLabel
        ///</summary>
        public string OptionChoiceLabel { get; set; }

        ///<summary>
        /// IsDropdown
        ///</summary>
        public bool IsDropdown { get; set; }

        ///<summary>
        /// QuestionId
        ///</summary>
        public int QuestionId { get; set; }

        ///<summary>
        /// CreatedOn
        ///</summary>
        public System.DateTime? CreatedOn { get; set; }

        ///<summary>
        /// ModifiedOn
        ///</summary>
        public System.DateTime? ModifiedOn { get; set; }

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Answer> Answers { get; set; } // Answer.FK_Answer_QuestionOption

        // Foreign keys
        public virtual Question Question { get; set; } // FK_dbo.QuestionOption_dbo.Question_QuestionId

        public QuestionOption()
        {
            Answers = new System.Collections.Generic.List<Answer>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
