// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{
    using System;

    // Question
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class Question
    {
        public int QuestionId { get; set; } // QuestionId (Primary key)
        public int PrecedingQuestionId { get; set; } // PrecedingQuestionId
        public string Code { get; set; } // Code
        public string QuestionText { get; set; } // QuestionText
        public bool Required { get; set; } // Required
        public bool OnlyNumericValue { get; set; } // OnlyNumericValue
        public bool IncludeComment { get; set; } // IncludeComment
        public string Comment { get; set; } // Comment
        public int QuestionOrder { get; set; } // QuestionOrder
        public int DependentQuestionId { get; set; } // DependentQuestionId
        public int DependentQuestionOptionId { get; set; } // DependentQuestionOptionId
        public bool AllowMultipleChoice { get; set; } // AllowMultipleChoice
        public int JumpQuestionId { get; set; } // JumpQuestionId
        public int JumpQuestionOptionId { get; set; } // JumpQuestionOptionId
        public bool HasPredefinedDropdown { get; set; } // HasPredefinedDropdown
        public int PredefinedDropdownId { get; set; } // PredefinedDropdownId
        public int SectionId { get; set; } // SectionId
        public int QuestionTypeId { get; set; } // QuestionTypeId
        public int RuleId { get; set; } // RuleId
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string ModifiedBy { get; set; } // ModifiedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string DeletedBy { get; set; } // DeletedBy
        public System.DateTime? DeletedOn { get; set; } // DeletedOn
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public bool IsUpdated { get; set; } // IsUpdated

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Answer> Answers { get; set; } // Answer.FK_Answer_Question
        public virtual System.Collections.Generic.ICollection<MatrixCol> MatrixCols { get; set; } // MatrixCol.FK_dbo.MatrixCol_dbo.Question_QuestionId
        public virtual System.Collections.Generic.ICollection<MatrixRow> MatrixRows { get; set; } // MatrixRow.FK_dbo.MatrixRow_dbo.Question_QuestionId
        public virtual System.Collections.Generic.ICollection<QuestionOption> QuestionOptions { get; set; } // QuestionOption.FK_dbo.QuestionOption_dbo.Question_QuestionId

        // Foreign keys
        public virtual QuestionType QuestionType { get; set; } // FK_dbo.Question_dbo.QuestionType_QuestionTypeId
        public virtual SurveySection SurveySection { get; set; } // FK_dbo.Question_dbo.SurveySection_SectionId

        public Question()
        {
            Answers = new System.Collections.Generic.List<Answer>();
            MatrixCols = new System.Collections.Generic.List<MatrixCol>();
            MatrixRows = new System.Collections.Generic.List<MatrixRow>();
            QuestionOptions = new System.Collections.Generic.List<QuestionOption>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
