// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class Question
    {
        public int QuestionId { get; set; }
        public int PrecedingQuestionId { get; set; }
        public string Code { get; set; }
        public string QuestionText { get; set; }
        public bool Required { get; set; }
        public bool OnlyNumericValue { get; set; }
        public bool IncludeComment { get; set; }
        public string Comment { get; set; }
        public int QuestionOrder { get; set; }
        public int DependentQuestionId { get; set; }
        public int DependentQuestionOptionId { get; set; }
        public bool AllowMultipleChoice { get; set; }
        public int JumpQuestionId { get; set; }
        public int JumpQuestionOptionId { get; set; }
        public bool HasPredefinedDropdown { get; set; }
        public int PredefinedDropdownId { get; set; }
        public int SectionId { get; set; }
        public int QuestionTypeId { get; set; }
        public int RuleId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime? CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime? ModifiedOn { get; set; }
        public string DeletedBy { get; set; }
        public System.DateTime? DeletedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsUpdated { get; set; }

        public virtual System.Collections.Generic.ICollection<Answer> Answers { get; set; }
        public virtual System.Collections.Generic.ICollection<MatrixCol> MatrixCols { get; set; }
        public virtual System.Collections.Generic.ICollection<MatrixRow> MatrixRows { get; set; }
        public virtual System.Collections.Generic.ICollection<QuestionOption> QuestionOptions { get; set; }

        public virtual QuestionType QuestionType { get; set; }
        public virtual SurveySection SurveySection { get; set; }

        public Question()
        {
            Answers = new System.Collections.Generic.List<Answer>();
            MatrixCols = new System.Collections.Generic.List<MatrixCol>();
            MatrixRows = new System.Collections.Generic.List<MatrixRow>();
            QuestionOptions = new System.Collections.Generic.List<QuestionOption>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
