// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    // QuestionOption
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class QuestionOptionMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<QuestionOption>
    {
        public QuestionOptionMapping()
            : this("dbo")
        {
        }

        public QuestionOptionMapping(string schema)
        {
            ToTable("QuestionOption", schema);
            HasKey(x => x.QuestionOptionId);

            Property(x => x.QuestionOptionId).HasColumnName(@"QuestionOptionId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.OptionChoiceLabel).HasColumnName(@"OptionChoiceLabel").IsOptional().HasColumnType("nvarchar");
            Property(x => x.IsDropdown).HasColumnName(@"IsDropdown").IsRequired().HasColumnType("bit");
            Property(x => x.QuestionId).HasColumnName(@"QuestionId").IsRequired().HasColumnType("int");
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").IsOptional().HasColumnType("datetime");
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").IsOptional().HasColumnType("datetime");

            // Foreign keys
            HasRequired(a => a.Question).WithMany(b => b.QuestionOptions).HasForeignKey(c => c.QuestionId); // FK_dbo.QuestionOption_dbo.Question_QuestionId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
