// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class QuestionType
    {
        public int QuestionTypeId { get; set; }
        public string Type { get; set; }

        public virtual System.Collections.Generic.ICollection<Question> Questions { get; set; }

        public QuestionType()
        {
            Questions = new System.Collections.Generic.List<Question>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
