// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    // Rule
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class Rule
    {

        ///<summary>
        /// RuleId (Primary key)
        ///</summary>
        public int RuleId { get; set; }

        ///<summary>
        /// Name
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        /// Description
        ///</summary>
        public string Description { get; set; }

        public Rule()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
