// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    // Survey
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class SurveyMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Survey>
    {
        public SurveyMapping()
            : this("dbo")
        {
        }

        public SurveyMapping(string schema)
        {
            ToTable("Survey", schema);
            HasKey(x => x.SurveyId);

            Property(x => x.SurveyId).HasColumnName(@"SurveyId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UniqueId).HasColumnName(@"UniqueId").IsOptional().HasColumnType("nvarchar");
            Property(x => x.Name).HasColumnName(@"Name").IsOptional().HasColumnType("nvarchar");
            Property(x => x.Description).HasColumnName(@"Description").IsOptional().HasColumnType("nvarchar");
            Property(x => x.Logo).HasColumnName(@"Logo").IsOptional().HasColumnType("nvarchar");
            Property(x => x.OrganizationId).HasColumnName(@"OrganizationId").IsRequired().HasColumnType("int");
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").IsOptional().HasColumnType("nvarchar");
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").IsOptional().HasColumnType("datetime");
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").IsOptional().HasColumnType("nvarchar");
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").IsOptional().HasColumnType("datetime");
            Property(x => x.DeletedBy).HasColumnName(@"DeletedBy").IsOptional().HasColumnType("nvarchar");
            Property(x => x.DeletedOn).HasColumnName(@"DeletedOn").IsOptional().HasColumnType("datetime");
            Property(x => x.IsActive).HasColumnName(@"IsActive").IsRequired().HasColumnType("bit");
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").IsRequired().HasColumnType("bit");

            // Foreign keys
            HasRequired(a => a.Organization).WithMany(b => b.Surveys).HasForeignKey(c => c.OrganizationId); // FK_dbo.Survey_dbo.Organization_OrganizationId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
