// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class SurveyComment
    {
        public int SurveyCommentsId { get; set; }
        public string SurveyeeGuid { get; set; }
        public int UserId { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public System.DateTime? Date { get; set; }

        public SurveyComment()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
