// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Data
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public int PwdChangeDays { get; set; }
        public int PwdChangeWarningDays { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime? CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime? ModifiedOn { get; set; }
        public string DeletedBy { get; set; }
        public System.DateTime? DeletedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }

        public virtual System.Collections.Generic.ICollection<Role> Roles { get; set; }
        public virtual System.Collections.Generic.ICollection<UserGroup> UserGroups { get; set; }
        public virtual System.Collections.Generic.ICollection<UserTablet> UserTablets { get; set; }

        public User()
        {
            UserGroups = new System.Collections.Generic.List<UserGroup>();
            UserTablets = new System.Collections.Generic.List<UserTablet>();
            Roles = new System.Collections.Generic.List<Role>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
