USE efdemocallback
GO

CREATE TABLE LiveQuizzes ( ID INT NOT NULL PRIMARY KEY IDENTITY(1,1), added DATETIME NOT NULL );
CREATE TABLE Courses     ( ID INT NOT NULL PRIMARY KEY IDENTITY(1,1), added DATETIME NOT NULL );
CREATE TABLE Treez       ( ID INT NOT NULL PRIMARY KEY IDENTITY(1,1), added DATETIME NOT NULL );
GO
