// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace MigrationDemo
{

    public class GetEngineerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GetEngineer>
    {
        public GetEngineerConfiguration()
            : this("dbo")
        {
        }
 
        public GetEngineerConfiguration(string schema)
        {
            ToTable(schema + ".get_engineers");
            HasKey(x => new { x.EngineerCompanyId, x.Description, x.EngineerPersonId, x.Forename, x.Surname });

            Property(x => x.EngineerCompanyId).HasColumnName("engineer_company_id").IsRequired().HasColumnType("int");
            Property(x => x.Description).HasColumnName("description").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.EngineerPersonId).HasColumnName("engineer_person_id").IsRequired().HasColumnType("int");
            Property(x => x.Forename).HasColumnName("forename").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Surname).HasColumnName("surname").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.MobilePhoneNumber).HasColumnName("mobile_phone_number").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
        }
    }

}
// </auto-generated>
