// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace MigrationDemo
{

    public class GetEngineer
    {
        public int EngineerCompanyId { get; set; }
        public string Description { get; set; }
        public int EngineerPersonId { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string MobilePhoneNumber { get; set; }
    }

}
// </auto-generated>
