// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace MigrationDemo
{

    public class TableWithSpaceInColumnOnlyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TableWithSpaceInColumnOnly>
    {
        public TableWithSpaceInColumnOnlyConfiguration()
            : this("dbo")
        {
        }
 
        public TableWithSpaceInColumnOnlyConfiguration(string schema)
        {
            ToTable(schema + ".TableWithSpaceInColumnOnly");
            HasKey(x => x.Idvalue);

            Property(x => x.Idvalue).HasColumnName("id value").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

}
// </auto-generated>
