// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Callbacks
{

    public interface IDb : System.IDisposable
    {
        System.Data.Entity.DbSet<Car> Car { get; set; } // Car
        System.Data.Entity.DbSet<Colour> Colour { get; set; } // Colour
        System.Data.Entity.DbSet<Courses> Courses { get; set; } // Courses
        System.Data.Entity.DbSet<LiveQuizzes> LiveQuizzes { get; set; } // LiveQuizzes
        System.Data.Entity.DbSet<OrderErrors> OrderErrors { get; set; } // tblOrderErrors
        System.Data.Entity.DbSet<OrderErrorsV2> OrderErrorsV2 { get; set; } // tblOrderErrorsAB_
        System.Data.Entity.DbSet<OrderLines> OrderLines { get; set; } // tblOrderLines
        System.Data.Entity.DbSet<OrderLinesV2> OrderLinesV2 { get; set; } // AB_OrderLinesAB_
        System.Data.Entity.DbSet<Orders> Orders { get; set; } // tblOrders
        System.Data.Entity.DbSet<OrdersV2> OrdersV2 { get; set; } // AB_OrdersAB_
        System.Data.Entity.DbSet<Symbols> Symbols { get; set; } // Symbols
        System.Data.Entity.DbSet<Trees> Trees { get; set; } // Treez

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        
        // Stored Procedures
        OrderDetailsReturnModel OrderDetails(int? orderId);
    }

}
// </auto-generated>
