// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Callbacks
{

    public class OrderDetailsReturnModel
    {
        public class ResultSetModel1
        {
            public System.Int32 ID { get; set; }
            public System.DateTime added { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

        public class ResultSetModel2
        {
            public System.Int32 ID { get; set; }
            public System.Int32 OrderID { get; set; }
            public System.String sku { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

        public class ResultSetModel3
        {
            public System.Int32 ID { get; set; }
            public System.Int32 OrderID { get; set; }
            public System.String error { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel3> ResultSet3;

    }

}
// </auto-generated>
