// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Callbacks
{

    // AB_OrdersAB_
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class OrdersV2 /* Column count = 2 */
    {
        // No of columns for table OrdersV2 = 2
        public static int ColumnCount = 2;

        [DemoAttribute] public int Id { get; set; } // ID (Primary key)
        public System.DateTime Added { get; set; } // added /*todo*/

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<OrderLinesV2> OrderLinesV2 { get; set; } // AB_OrderLinesAB_.AB_OrderLinesAB_FK
        
        public OrdersV2()
        {
            OrderLinesV2 = new System.Collections.Generic.List<OrderLinesV2>();
        }
    }

}
// </auto-generated>
