// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Callbacks
{

    // tblOrders
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.18.1.0")]
    public class Orders /* Column count = 2 */
    {
        // No of columns for table Orders = 2
        public static int ColumnCount = 2;

        [DemoAttribute] public int Id { get; set; } // ID (Primary key)
        public System.DateTime Added { get; set; } // added /*todo*/

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<OrderLines> OrderLines { get; set; } // tblOrderLines.tblOrdersFK
        
        public Orders()
        {
            OrderLines = new System.Collections.Generic.List<OrderLines>();
        }
    }

}
// </auto-generated>
