// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Callbacks
{

    // Symbols
    public class Symbols /* Column count = 4 */
    {
        // No of columns for table Symbols = 4
        public static int ColumnCount = 4;

        public int Dollar { get; set; } // $ (Primary key) /*todo*/
        public int? Percent { get; set; } // % /*todo*/
        public int? Pound { get; set; } // £ /*todo*/
        public int? Callback { get; set; } // &callbacks$ /*todo*/
    }

}
// </auto-generated>
