// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Configuration
{
    using System;

    // Answer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class AnswerMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Answer>
    {
        public AnswerMapping()
            : this("dbo")
        {
        }

        public AnswerMapping(string schema)
        {
            ToTable("Answer", schema);
            HasKey(x => x.AnswerId);

            Property(x => x.AnswerId).HasColumnName(@"AnswerId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.QuestionId).HasColumnName(@"QuestionId").IsOptional().HasColumnType("int");
            Property(x => x.QuestionOptionId).HasColumnName(@"QuestionOptionId").IsOptional().HasColumnType("int");
            Property(x => x.AnswerValue).HasColumnName(@"AnswerValue").IsOptional().HasColumnType("nvarchar");
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").IsOptional().HasColumnType("nvarchar");
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").IsRequired().HasColumnType("datetime");
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").IsOptional().HasColumnType("nvarchar");
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").IsOptional().HasColumnType("datetime");
            Property(x => x.DeletedBy).HasColumnName(@"DeletedBy").IsOptional().HasColumnType("nvarchar");
            Property(x => x.DeletedOn).HasColumnName(@"DeletedOn").IsOptional().HasColumnType("datetime");
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").IsOptional().HasColumnType("bit");
            Property(x => x.Comment).HasColumnName(@"Comment").IsOptional().HasColumnType("nvarchar");
            Property(x => x.SurveyeeGuid).HasColumnName(@"SurveyeeGuid").IsRequired().IsFixedLength().IsUnicode(false).HasColumnType("char").HasMaxLength(36);
            Property(x => x.MatrixColId).HasColumnName(@"MatrixColId").IsOptional().HasColumnType("int");
            Property(x => x.MatrixRowId).HasColumnName(@"MatrixRowId").IsOptional().HasColumnType("int");

            // Foreign keys
            HasOptional(a => a.Question).WithMany(b => b.Answers).HasForeignKey(c => c.QuestionId).WillCascadeOnDelete(false); // FK_Answer_Question
            HasOptional(a => a.QuestionOption).WithMany(b => b.Answers).HasForeignKey(c => c.QuestionOptionId).WillCascadeOnDelete(false); // FK_Answer_QuestionOption
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
