// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Configuration
{
    using System;

    // MatrixCol
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class MatrixColMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MatrixCol>
    {
        public MatrixColMapping()
            : this("dbo")
        {
        }

        public MatrixColMapping(string schema)
        {
            ToTable("MatrixCol", schema);
            HasKey(x => x.ColumnId);

            Property(x => x.ColumnId).HasColumnName(@"ColumnId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ColumnLabel).HasColumnName(@"ColumnLabel").IsOptional().HasColumnType("nvarchar");
            Property(x => x.QuestionId).HasColumnName(@"QuestionId").IsRequired().HasColumnType("int");
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").IsOptional().HasColumnType("datetime");
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").IsOptional().HasColumnType("datetime");

            // Foreign keys
            HasRequired(a => a.Question).WithMany(b => b.MatrixCols).HasForeignKey(c => c.QuestionId); // FK_dbo.MatrixCol_dbo.Question_QuestionId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
