// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Configuration
{
    using System;

    // SurveyComment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class SurveyCommentMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SurveyComment>
    {
        public SurveyCommentMapping()
            : this("dbo")
        {
        }

        public SurveyCommentMapping(string schema)
        {
            ToTable("SurveyComment", schema);
            HasKey(x => x.SurveyCommentsId);

            Property(x => x.SurveyCommentsId).HasColumnName(@"SurveyCommentsId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SurveyeeGuid).HasColumnName(@"SurveyeeGuid").IsRequired().IsFixedLength().IsUnicode(false).HasColumnType("char").HasMaxLength(36);
            Property(x => x.UserId).HasColumnName(@"UserId").IsRequired().HasColumnType("int");
            Property(x => x.Comment).HasColumnName(@"Comment").IsRequired().IsUnicode(false).HasColumnType("varchar");
            Property(x => x.Status).HasColumnName(@"Status").IsOptional().IsFixedLength().HasColumnType("nchar").HasMaxLength(10);
            Property(x => x.Date).HasColumnName(@"Date").IsOptional().HasColumnType("datetime");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
