// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ReversePocoGenerationSample.Configuration
{
    using System;

    // SurveyeeSurveyComment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class SurveyeeSurveyCommentMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SurveyeeSurveyComment>
    {
        public SurveyeeSurveyCommentMapping()
            : this("dbo")
        {
        }

        public SurveyeeSurveyCommentMapping(string schema)
        {
            ToTable("SurveyeeSurveyComment", schema);
            HasKey(x => x.CommentId);

            Property(x => x.CommentId).HasColumnName(@"CommentId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SurveyeeId).HasColumnName(@"SurveyeeId").IsRequired().HasColumnType("int");
            Property(x => x.SurveyId).HasColumnName(@"SurveyId").IsRequired().HasColumnType("int");
            Property(x => x.Comment).HasColumnName(@"Comment").IsRequired().HasColumnType("nvarchar");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
