// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace MigrationDemo
{

    public class EngineerPersonConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EngineerPerson>
    {
        public EngineerPersonConfiguration()
            : this("dbo")
        {
        }
 
        public EngineerPersonConfiguration(string schema)
        {
            ToTable(schema + ".engineer_person");
            HasKey(x => x.EngineerPersonId);

            Property(x => x.EngineerPersonId).HasColumnName("engineer_person_id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EngineerCompanyId).HasColumnName("engineer_company_id").IsRequired().HasColumnType("int");
            Property(x => x.Forename).HasColumnName("forename").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Surname).HasColumnName("surname").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.MobilePhoneNumber).HasColumnName("mobile_phone_number").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Fieldwithspaces).HasColumnName("field with spaces").IsOptional().HasColumnType("int");

            HasRequired(a => a.EngineerCompany).WithMany(b => b.EngineerPersons).HasForeignKey(c => c.EngineerCompanyId);
        }
    }

}
// </auto-generated>
