// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace MigrationDemo
{

    public class SymbolConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Symbol>
    {
        public SymbolConfiguration()
            : this("dbo")
        {
        }
 
        public SymbolConfiguration(string schema)
        {
            ToTable(schema + ".symbols");
            HasKey(x => x.C36);

            Property(x => x.C36).HasColumnName("$").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.C37).HasColumnName("%").IsOptional().HasColumnType("int");
            Property(x => x.C163).HasColumnName("£").IsOptional().HasColumnType("int");
            Property(x => x.C38Test36).HasColumnName("&test$").IsOptional().HasColumnType("int");
            Property(x => x.Description).HasColumnName("description").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(20);
        }
    }

}
// </auto-generated>
